import type { Post } from './types';

export const MOCK_POSTS: Post[] = [
  {
    id: 1,
    title: 'His mother had always taught him',
    body: "His mother had always taught him not to ever think of himself as better than others. He'd tried to live by this motto.",
    tags: ['history', 'american', 'crime'],
    likes: 192,
    views: 305,
  },
  {
    id: 2,
    title: 'He was an expert but not in a discipline',
    body: 'He was an expert but not in a discipline that anyone could fully appreciate. He knew how to hold the cone just right.',
    tags: ['french', 'fiction', 'english'],
    likes: 859,
    views: 4884,
  },
  {
    id: 3,
    title: 'Dave watched as the forest burned up on the hill.',
    body: 'Dave watched as the forest burned up on the hill, only a few miles from his house. The car had been hastily packed.',
    tags: ['magical', 'history', 'french'],
    likes: 1448,
    views: 4784,
  },
  {
    id: 4,
    title: 'The morning train was late again',
    body: 'The platform filled with people who had all decided, at the same moment, that today they would complain about it.',
    tags: ['fiction', 'city'],
    likes: 312,
    views: 1204,
  },
  {
    id: 5,
    title: 'A garden that grows at night',
    body: 'Nobody in the village could explain why the flowers only opened after midnight, so they stopped trying.',
    tags: ['nature', 'magical'],
    likes: 640,
    views: 2210,
  },
  {
    id: 6,
    title: 'Letters from the old lighthouse',
    body: 'Every winter a new letter arrived, sealed with wax and signed with a single initial nobody recognised.',
    tags: ['history', 'love'],
    likes: 505,
    views: 1873,
  },
  {
    id: 7,
    title: 'The detective who hated coffee',
    body: 'She solved every case before lunch, mostly because she refused to waste mornings standing in queues.',
    tags: ['crime', 'fiction'],
    likes: 977,
    views: 3650,
  },
  {
    id: 8,
    title: 'Maps of places that do not exist',
    body: 'The atlas had forty pages, and only thirty-nine of them matched anything on the real coastline.',
    tags: ['adventure', 'fiction'],
    likes: 421,
    views: 1398,
  },
  {
    id: 9,
    title: 'A quiet street in Paris',
    body: 'The bakery on the corner opened at six, and by seven the whole street smelled of warm butter.',
    tags: ['french', 'city', 'love'],
    likes: 733,
    views: 2951,
  },
  {
    id: 10,
    title: 'The last summer before the storm',
    body: "They spent the whole summer on the lake, pretending the clouds on the horizon were someone else's problem.",
    tags: ['nature', 'memory'],
    likes: 288,
    views: 990,
  },
  {
    id: 11,
    title: 'Notes on building a small boat',
    body: 'The first boat sank in ten minutes. The second one lasted an hour, which everyone agreed was progress.',
    tags: ['adventure', 'english'],
    likes: 356,
    views: 1127,
  },
  {
    id: 12,
    title: 'The museum after closing time',
    body: 'The night guard swore the portraits changed expressions, but only when nobody else was looking.',
    tags: ['history', 'mystery'],
    likes: 1102,
    views: 4015,
  },
];
